### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chaufanglin** [ms-dot-k/AVSR#1]
Hi Minsu,

Nice work! I wanted to run your trained models, but I got this error:
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (CPU)

The detailed error is 
>   File "/home/zhaofeng/research/kaist-avsr/espnet/nets/beam_search.py", line 373, in forward
>     running_hyps = self.post_process(i, maxlen, maxlenratio, best, ended_hyps)
>   File "/home/zhaofeng/research/kaist-avsr/espnet/nets/batch_beam_search.py", line 348, in post_process
>     return self._batch_select(running_hyps, remained_ids)
>   File "/home/zhaofeng/research/kaist-avsr/espnet/nets/batch_beam_search.py", line 51, in _batch_select
>     score=hyps.score[ids],
> RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

When I tried to debug, it seemed hyps.score was on CPU and ids was on GPU, which led to this error. 
Could you please help me out a bit?

Many thanks
Zhaofeng

**Comment by ms-dot-k** [comment]
Hi Zhaofeng,

Can you check from where the output starts on the CPU rather than the GPU?

**Comment by chaufanglin** [comment]
Hi Minsu, 

Thanks for responding. I'm not sure if I understand it correctly. So when initializing running_hyps in beam_search.py row 367, the score is not on CPU. But I don't know if this is an espnet problem or anything.

**Comment by ms-dot-k** [comment]
Hi,

Can you try to modify `espnet/nets/batch_beam_search.py` line 347 by adding `.cpu()` as below
```
        remained_ids = torch.nonzero(is_eos == 0, as_tuple=False).view(-1).cpu()
```

**Comment by chaufanglin** [comment]
Hi,
Thanks! It works now. 

Many thanks,
Zhaofeng
